import os
import time
import gc

# Disable model source check to speed up initialization
os.environ["PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK"] = "True"

import paddle
from paddleocr import PaddleOCR
import cv2
import numpy as np

# 1. Initialize once globally
ocr = PaddleOCR(
    lang='hi',
    use_angle_cls=True,                  # Handle rotated text
    use_doc_orientation_classify=False,  # Skip document-level orientation (heavy)
    use_doc_unwarping=False,             # Skip warping correction
)

def safe_resize(image_path):
    """
    Never feed 12MP image into OCR.
    Cap longest side at 1400px.
    """
    max_dim = 1400  # absolute cap
    
    # Read image with OpenCV
    # We use cv2 because PaddleOCR natively uses numpy arrays generated by cv2 anyway. 
    image = cv2.imread(image_path)
    if image is None:
        raise ValueError(f"Could not read image: {image_path}")

    h, w = image.shape[:2]
    original_size = f"{w}x{h}"
    max_current = max(h, w)

    if max_current > max_dim:
        scale = max_dim / max_current
        image = cv2.resize(image, None, fx=scale, fy=scale)
        
    new_h, new_w = image.shape[:2]
    resized_size = f"{new_w}x{new_h}"

    return image, original_size, resized_size

def run_ocr(image_path):
    """
    Returns:
    {
        "raw_text": "...",
        "blocks": [...],
        "time_taken": float,
        "device": "..."
    }
    """
    try:
        # Step 2: Safe resize
        image, original_size, resized_size = safe_resize(image_path)
        
        # Step 4: Accurate timing
        start = time.perf_counter()
        
        # We pass the pre-resized numpy array directly to paddleocr
        try:
            # 3.4+ API
            result = list(ocr.predict(image))
            is_predict = True
        except AttributeError:
            # < 2.x API
            result = ocr.ocr(image, cls=True)
            is_predict = False

        end = time.perf_counter()
        execution_time = end - start
        
        lines_out = []
        blocks = []
        
        if is_predict:
            for page in result:
                if not page:
                    continue
                rec_texts = page.get("rec_texts", [])
                rec_scores = page.get("rec_scores", [])
                dt_polys = page.get("dt_polys", [])
                
                for text, score, bbox in zip(rec_texts, rec_scores, dt_polys):
                    text = text.strip()
                    if text:
                        lines_out.append(text)
                        blocks.append({
                            "text": text,
                            "confidence": round(float(score), 3),
                            "bbox": bbox
                        })
        else:
            if result and result[0]:
                for line in result[0]:
                    bbox, (text, conf) = line[0], line[1]
                    text = text.strip()
                    if text:
                        lines_out.append(text)
                        blocks.append({
                            "text": text,
                            "confidence": round(float(conf), 3),
                            "bbox": bbox
                        })

        raw_text = "\n".join(lines_out)
        
        # Memory cleanup
        # This keeps the environment safe without reinitializing models.
        del image
        gc.collect()

        import paddleocr
        return {
            "engine": "paddle_hindi",
            "paddle_version": paddle.__version__,
            "device": str(paddle.device.get_device()),
            "image_original_size": original_size,
            "image_resized_size": resized_size,
            "time_taken": round(execution_time, 2),
            "block_count": len(blocks),
            "raw_text": raw_text,
            "blocks": blocks
        }
        
    except Exception as e:
        import traceback
        return {
            "engine": "paddle_hindi",
            "error": str(e),
            "traceback": traceback.format_exc(),
            "time_taken": 0
        }
